# netlify.toml - Configuration for deploying to Netlify

[build]
  # This command tells Netlify to install the Python packages.
  command = "pip install -r requirements.txt"
  # This specifies the directory where your serverless function is located.
  # Netlify will look for your api.py file inside this directory.
  functions = "api/"

# This rule rewrites all incoming requests to your serverless function,
# effectively turning your site into a full-fledged API.
[[redirects]]
  from = "/*"
  to = "/api/main" # This should match the name of your handler file (api.py -> /api/api)
  status = 200
